In [62]:
import pandas as pd
import numpy as np
import datetime as dt

In [64]:
child = pd.read_excel('assignment_data.xlsx')
trainers = pd.read_excel('Trainers.xlsx')
booked = pd.read_excel('Booked_Users.xlsx')
subs = pd.read_excel('Subscrption.xlsx')
trainers

,Trainer Name,Date,Timing,Grade,Batch size,Batch count,Batch,Topics
0,FAC_5001,16 April Thursday,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial I,Rocking with rhymes
1,FAC_5002,16 April Thursday,11.15 am - 12 noon,"Grade 3,4",group,9.0,trial I,In my mind's eye
2,FAC_5003,16 April Thursday,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial II,Word Whiz
3,FAC_5006,16 April Thursday,11.15 am - 12 noon,"Grade 3,4",group,7.0,trial II,Rocking with rhymes
4,FAC_5007,16 April Thursday,4:00-4:45 pm,"Grade 3,4",group,9.0,trial I,In my head or real
...,...,...,...,...,...,...,...,...
169,FAC_5009,27 April Monday,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial IV,Emotional energy
170,FAC_5040,27 April Monday,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial IV,In my mind's eye
171,FAC_5038,27 April Monday,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial II,Play with Punctuation
172,FAC_5002,27 April Monday,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial II,Word Whiz
173,FAC_5022,27 April Monday,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial III,Rocking with rhymes

In [65]:
trainers['Date'] = trainers['Date'].str[:2]
trainers

,Trainer Name,Date,Timing,Grade,Batch size,Batch count,Batch,Topics
0,FAC_5001,16,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial I,Rocking with rhymes
1,FAC_5002,16,11.15 am - 12 noon,"Grade 3,4",group,9.0,trial I,In my mind's eye
2,FAC_5003,16,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial II,Word Whiz
3,FAC_5006,16,11.15 am - 12 noon,"Grade 3,4",group,7.0,trial II,Rocking with rhymes
4,FAC_5007,16,4:00-4:45 pm,"Grade 3,4",group,9.0,trial I,In my head or real
...,...,...,...,...,...,...,...,...
169,FAC_5009,27,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial IV,Emotional energy
170,FAC_5040,27,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial IV,In my mind's eye
171,FAC_5038,27,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial II,Play with Punctuation
172,FAC_5002,27,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial II,Word Whiz
173,FAC_5022,27,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial III,Rocking with rhymes

In [53]:
booked = pd.read_excel('Booked_Users.xlsx')

In [16]:
display(trainers)
display(subs)
display(booked)

,Trainer Name,Date,Timing,Grade,Batch size,Batch count,Batch,Topics
0,FAC_5001,16 April Thursday,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial I,Rocking with rhymes
1,FAC_5002,16 April Thursday,11.15 am - 12 noon,"Grade 3,4",group,9.0,trial I,In my mind's eye
2,FAC_5003,16 April Thursday,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial II,Word Whiz
3,FAC_5006,16 April Thursday,11.15 am - 12 noon,"Grade 3,4",group,7.0,trial II,Rocking with rhymes
4,FAC_5007,16 April Thursday,4:00-4:45 pm,"Grade 3,4",group,9.0,trial I,In my head or real
...,...,...,...,...,...,...,...,...
169,FAC_5009,27 April Monday,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial IV,Emotional energy
170,FAC_5040,27 April Monday,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial IV,In my mind's eye
171,FAC_5038,27 April Monday,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial II,Play with Punctuation
172,FAC_5002,27 April Monday,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial II,Word Whiz
173,FAC_5022,27 April Monday,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial III,Rocking with rhymes

,Child Name,Registered Number,Registered Email ID,Payment date,Sale by,Grade,Pricing,Duration,Sessions preferred,Live session details
0,CH_31846,9.111002e+11,s2m_test_21890@tests2m.com,16-03-2020 12:00:00 AM,SP_1001,2,199,0.5,NaN,NaN
1,CH_31847,9.111002e+11,NaN,16-03-2020 12:00:00 AM,SP_1002,4,199,0.5,NaN,NaN
2,CH_31848,9.111002e+11,s2m_test_21891@tests2m.com,16-03-2020 12:00:00 AM,NaN,4,199,0.5,NaN,NaN
3,CH_31849,9.111002e+11,s2m_test_21440@tests2m.com,16-03-2020 12:00:00 AM,SP_1004,3,199,0.5,NaN,NaN
4,CH_31850,9.111002e+11,s2m_test_21892@tests2m.com,17-03-2020 12:00:00 AM,NaN,5,199,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
413,CH_32081,9.111002e+11,s2m_test_22161@tests2m.com,2020-04-27 00:00:00,SP_1005,2,1999,12G + 1yr,Assigned,NaN
414,CH_32082,9.111002e+11,s2m_test_22162@tests2m.com,2020-04-27 00:00:00,SP_1012,3,1999,10G +1 yr,Assigned,NaN
415,CH_31831,9.111002e+11,s2m_test_21876@tests2m.com,2020-04-27 00:00:00,SP_1005,3,1999,14G + 1yr,Assigned,NaN
416,CH_32079,9.111002e+11,s2m_test_22158@tests2m.com,2020-04-27 00:00:00,SP_1005,2,1999,12G + 1yr,NaN,NaN
417,CH_32083,9.111002e+11,s2m_test_21404@tests2m.com,2020-04-27 00:00:00,SP_1012,4,1999,10G + 1Yr,Morning,NaN

,Invitee UUID,Batch,Enrolment Type,Child Name,Grade,School,Phone,Parent Email,Opted Start Time,Opted Start Date,Facilitator UUID,Attendance
0,AGIV7AYTBF4ZA6SA,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31440,Grade 2,DPS,911100222445,s2m_test_21459@tests2m.com,16-04-2020 11:15:00,"11:15am - Thursday, April 16, 2020",AEFDOHX57EFVUS2G,Present
1,HAPQZDZXDJPMFZ73,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31441,Grade 2,DPS,911100222446,s2m_test_21460@tests2m.com,16-04-2020 11:15:00,"11:15am - Thursday, April 16, 2020",AEFDOHX57EFVUS2G,Present
2,AHLT5B5XGJTONPE3,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31442,Grade 2,City Montessori school lucknow,911100222447,s2m_test_21461@tests2m.com,16-04-2020 11:15:00,"11:15am - Thursday, April 16, 2020",AEFDOHX57EFVUS2G,Absent
3,HCNR5B2SFMSX727O,"fREADom Trial - Grades 3, 4 [I] 11:15am - Thu...",Trial,CH_31443,Grade 4,Reliance Foundation,911100222448,s2m_test_21462@tests2m.com,16-04-2020 11:15:00,"11:15am - Thursday, April 16, 2020",CDBCIBX6WD5NGCEZ,Absent
4,BFIT2F3UDJ5MV5GT,"fREADom Trial - Grades 3, 4 [I] 11:15am - Thu...",Trial,CH_31444,Grade 3,KRS,911100222449,s2m_test_21463@tests2m.com,16-04-2020 11:15:00,"11:15am - Thursday, April 16, 2020",CDBCIBX6WD5NGCEZ,Present
...,...,...,...,...,...,...,...,...,...,...,...,...
1706,BBJSY3OJTAA54LMV,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31382,Grade 1,Delhi public school north bangalore,911100222386,s2m_test_21399@tests2m.com,27-04-2020 18:00:00,"06:00pm - Monday, April 27, 2020",EBFFJCZNGZSMS7XU,NaN
1707,FHMX5ZJKVGJOUQTF,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31347,Grade 1,Nan group of school,911100222348,s2m_test_21360@tests2m.com,27-04-2020 18:00:00,"06:00pm - Monday, April 27, 2020",EBFFJCZNGZSMS7XU,NaN
1708,DHMW43JNVC5SDZ6D,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31346,Grade 2,Sri kumarans child home,911100222347,s2m_test_21359@tests2m.com,27-04-2020 18:00:00,"06:00pm - Monday, April 27, 2020",EBFFJCZNGZSMS7XU,NaN
1709,ACIW47ILSKFJ2WPS,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31315,Grade 2,Calarox public school,911100222312,s2m_test_21325@tests2m.com,27-04-2020 18:00:00,"06:00pm - Monday, April 27, 2020",EBFFJCZNGZSMS7XU,NaN
1710,GANT23JJWJNWRGUH,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Duplicate - Trial,CH_31402,Grade 1,SSRVM,911100222408,s2m_test_21422@tests2m.com,27-04-2020 18:00:00,"06:00pm - Monday, April 27, 2020",EBFFJCZNGZSMS7XU,NaN

In [54]:
booked['Opted Start Date'] = booked['Opted Start Time'].str[:2]

In [48]:
booked

,Invitee UUID,Batch,Enrolment Type,Child Name,Grade,School,Phone,Parent Email,Opted Start Time,Opted Start Date,Facilitator UUID,Attendance
0,AGIV7AYTBF4ZA6SA,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31440,Grade 2,DPS,911100222445,s2m_test_21459@tests2m.com,16-04-2020 11:15:00,16,AEFDOHX57EFVUS2G,Present
1,HAPQZDZXDJPMFZ73,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31441,Grade 2,DPS,911100222446,s2m_test_21460@tests2m.com,16-04-2020 11:15:00,16,AEFDOHX57EFVUS2G,Present
2,AHLT5B5XGJTONPE3,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31442,Grade 2,City Montessori school lucknow,911100222447,s2m_test_21461@tests2m.com,16-04-2020 11:15:00,16,AEFDOHX57EFVUS2G,Absent
3,HCNR5B2SFMSX727O,"fREADom Trial - Grades 3, 4 [I] 11:15am - Thu...",Trial,CH_31443,Grade 4,Reliance Foundation,911100222448,s2m_test_21462@tests2m.com,16-04-2020 11:15:00,16,CDBCIBX6WD5NGCEZ,Absent
4,BFIT2F3UDJ5MV5GT,"fREADom Trial - Grades 3, 4 [I] 11:15am - Thu...",Trial,CH_31444,Grade 3,KRS,911100222449,s2m_test_21463@tests2m.com,16-04-2020 11:15:00,16,CDBCIBX6WD5NGCEZ,Present
...,...,...,...,...,...,...,...,...,...,...,...,...
1706,BBJSY3OJTAA54LMV,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31382,Grade 1,Delhi public school north bangalore,911100222386,s2m_test_21399@tests2m.com,27-04-2020 18:00:00,27,EBFFJCZNGZSMS7XU,NaN
1707,FHMX5ZJKVGJOUQTF,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31347,Grade 1,Nan group of school,911100222348,s2m_test_21360@tests2m.com,27-04-2020 18:00:00,27,EBFFJCZNGZSMS7XU,NaN
1708,DHMW43JNVC5SDZ6D,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31346,Grade 2,Sri kumarans child home,911100222347,s2m_test_21359@tests2m.com,27-04-2020 18:00:00,27,EBFFJCZNGZSMS7XU,NaN
1709,ACIW47ILSKFJ2WPS,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31315,Grade 2,Calarox public school,911100222312,s2m_test_21325@tests2m.com,27-04-2020 18:00:00,27,EBFFJCZNGZSMS7XU,NaN
1710,GANT23JJWJNWRGUH,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Duplicate - Trial,CH_31402,Grade 1,SSRVM,911100222408,s2m_test_21422@tests2m.com,27-04-2020 18:00:00,27,EBFFJCZNGZSMS7XU,NaN

In [55]:
booked['Opted Start Time'] = booked['Opted Start Time'].str[-8:-3]
booked

,Invitee UUID,Batch,Enrolment Type,Child Name,Grade,School,Phone,Parent Email,Opted Start Time,Opted Start Date,Facilitator UUID,Attendance
0,AGIV7AYTBF4ZA6SA,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31440,Grade 2,DPS,911100222445,s2m_test_21459@tests2m.com,11:15,16,AEFDOHX57EFVUS2G,Present
1,HAPQZDZXDJPMFZ73,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31441,Grade 2,DPS,911100222446,s2m_test_21460@tests2m.com,11:15,16,AEFDOHX57EFVUS2G,Present
2,AHLT5B5XGJTONPE3,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31442,Grade 2,City Montessori school lucknow,911100222447,s2m_test_21461@tests2m.com,11:15,16,AEFDOHX57EFVUS2G,Absent
3,HCNR5B2SFMSX727O,"fREADom Trial - Grades 3, 4 [I] 11:15am - Thu...",Trial,CH_31443,Grade 4,Reliance Foundation,911100222448,s2m_test_21462@tests2m.com,11:15,16,CDBCIBX6WD5NGCEZ,Absent
4,BFIT2F3UDJ5MV5GT,"fREADom Trial - Grades 3, 4 [I] 11:15am - Thu...",Trial,CH_31444,Grade 3,KRS,911100222449,s2m_test_21463@tests2m.com,11:15,16,CDBCIBX6WD5NGCEZ,Present
...,...,...,...,...,...,...,...,...,...,...,...,...
1706,BBJSY3OJTAA54LMV,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31382,Grade 1,Delhi public school north bangalore,911100222386,s2m_test_21399@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN
1707,FHMX5ZJKVGJOUQTF,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31347,Grade 1,Nan group of school,911100222348,s2m_test_21360@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN
1708,DHMW43JNVC5SDZ6D,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31346,Grade 2,Sri kumarans child home,911100222347,s2m_test_21359@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN
1709,ACIW47ILSKFJ2WPS,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31315,Grade 2,Calarox public school,911100222312,s2m_test_21325@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN
1710,GANT23JJWJNWRGUH,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Duplicate - Trial,CH_31402,Grade 1,SSRVM,911100222408,s2m_test_21422@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN

In [50]:
trainers['time_upper'] = trainers['Timing'].str[:5]
trainers['time_lower'] = trainers['Timing'].str[-8:-2]

In [42]:
trainers['Date'] = trainers['Date'].str[:2]
trainers

,Trainer Name,Date,Timing,Grade,Batch size,Batch count,Batch,Topics,time_upper,time_lower
0,FAC_5001,16,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial I,Rocking with rhymes,11.15,12 no
1,FAC_5002,16,11.15 am - 12 noon,"Grade 3,4",group,9.0,trial I,In my mind's eye,11.15,12 no
2,FAC_5003,16,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial II,Word Whiz,11.15,12 no
3,FAC_5006,16,11.15 am - 12 noon,"Grade 3,4",group,7.0,trial II,Rocking with rhymes,11.15,12 no
4,FAC_5007,16,4:00-4:45 pm,"Grade 3,4",group,9.0,trial I,In my head or real,4:00-,-4:45
...,...,...,...,...,...,...,...,...,...,...
169,FAC_5009,27,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial IV,Emotional energy,6.00,6.45 p
170,FAC_5040,27,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial IV,In my mind's eye,6.00,6.45 p
171,FAC_5038,27,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial II,Play with Punctuation,6.00,6.45 p
172,FAC_5002,27,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial II,Word Whiz,6.00,6.45 p
173,FAC_5022,27,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial III,Rocking with rhymes,6.00,6.45 p

In [56]:
display(booked)
display(trainers)
display(subs)

,Invitee UUID,Batch,Enrolment Type,Child Name,Grade,School,Phone,Parent Email,Opted Start Time,Opted Start Date,Facilitator UUID,Attendance
0,AGIV7AYTBF4ZA6SA,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31440,Grade 2,DPS,911100222445,s2m_test_21459@tests2m.com,11:15,16,AEFDOHX57EFVUS2G,Present
1,HAPQZDZXDJPMFZ73,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31441,Grade 2,DPS,911100222446,s2m_test_21460@tests2m.com,11:15,16,AEFDOHX57EFVUS2G,Present
2,AHLT5B5XGJTONPE3,"fREADom Trial Class - Grades 1, 2 [I] 11:15am ...",Trial,CH_31442,Grade 2,City Montessori school lucknow,911100222447,s2m_test_21461@tests2m.com,11:15,16,AEFDOHX57EFVUS2G,Absent
3,HCNR5B2SFMSX727O,"fREADom Trial - Grades 3, 4 [I] 11:15am - Thu...",Trial,CH_31443,Grade 4,Reliance Foundation,911100222448,s2m_test_21462@tests2m.com,11:15,16,CDBCIBX6WD5NGCEZ,Absent
4,BFIT2F3UDJ5MV5GT,"fREADom Trial - Grades 3, 4 [I] 11:15am - Thu...",Trial,CH_31444,Grade 3,KRS,911100222449,s2m_test_21463@tests2m.com,11:15,16,CDBCIBX6WD5NGCEZ,Present
...,...,...,...,...,...,...,...,...,...,...,...,...
1706,BBJSY3OJTAA54LMV,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31382,Grade 1,Delhi public school north bangalore,911100222386,s2m_test_21399@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN
1707,FHMX5ZJKVGJOUQTF,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31347,Grade 1,Nan group of school,911100222348,s2m_test_21360@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN
1708,DHMW43JNVC5SDZ6D,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31346,Grade 2,Sri kumarans child home,911100222347,s2m_test_21359@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN
1709,ACIW47ILSKFJ2WPS,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Trial,CH_31315,Grade 2,Calarox public school,911100222312,s2m_test_21325@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN
1710,GANT23JJWJNWRGUH,"fREADom Trial - Grades 1,2 [III] 06:00pm - Mon...",Duplicate - Trial,CH_31402,Grade 1,SSRVM,911100222408,s2m_test_21422@tests2m.com,18:00,27,EBFFJCZNGZSMS7XU,NaN

,Trainer Name,Date,Timing,Grade,Batch size,Batch count,Batch,Topics,time_upper,time_lower
0,FAC_5001,16,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial I,Rocking with rhymes,11.15,12 no
1,FAC_5002,16,11.15 am - 12 noon,"Grade 3,4",group,9.0,trial I,In my mind's eye,11.15,12 no
2,FAC_5003,16,11.15 am - 12 noon,"Grade 1,2",group,9.0,trial II,Word Whiz,11.15,12 no
3,FAC_5006,16,11.15 am - 12 noon,"Grade 3,4",group,7.0,trial II,Rocking with rhymes,11.15,12 no
4,FAC_5007,16,4:00-4:45 pm,"Grade 3,4",group,9.0,trial I,In my head or real,4:00-,-4:45
...,...,...,...,...,...,...,...,...,...,...
169,FAC_5009,27,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial IV,Emotional energy,6.00,6.45 p
170,FAC_5040,27,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial IV,In my mind's eye,6.00,6.45 p
171,FAC_5038,27,6.00 pm - 6.45 pm,"Grade 3,4",NaN,NaN,Trial II,Play with Punctuation,6.00,6.45 p
172,FAC_5002,27,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial II,Word Whiz,6.00,6.45 p
173,FAC_5022,27,6.00 pm - 6.45 pm,"Grade 1,2",NaN,NaN,Trial III,Rocking with rhymes,6.00,6.45 p

,Child Name,Registered Number,Registered Email ID,Payment date,Sale by,Grade,Pricing,Duration,Sessions preferred,Live session details
0,CH_31846,9.111002e+11,s2m_test_21890@tests2m.com,16-03-2020 12:00:00 AM,SP_1001,2,199,0.5,NaN,NaN
1,CH_31847,9.111002e+11,NaN,16-03-2020 12:00:00 AM,SP_1002,4,199,0.5,NaN,NaN
2,CH_31848,9.111002e+11,s2m_test_21891@tests2m.com,16-03-2020 12:00:00 AM,NaN,4,199,0.5,NaN,NaN
3,CH_31849,9.111002e+11,s2m_test_21440@tests2m.com,16-03-2020 12:00:00 AM,SP_1004,3,199,0.5,NaN,NaN
4,CH_31850,9.111002e+11,s2m_test_21892@tests2m.com,17-03-2020 12:00:00 AM,NaN,5,199,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
413,CH_32081,9.111002e+11,s2m_test_22161@tests2m.com,2020-04-27 00:00:00,SP_1005,2,1999,12G + 1yr,Assigned,NaN
414,CH_32082,9.111002e+11,s2m_test_22162@tests2m.com,2020-04-27 00:00:00,SP_1012,3,1999,10G +1 yr,Assigned,NaN
415,CH_31831,9.111002e+11,s2m_test_21876@tests2m.com,2020-04-27 00:00:00,SP_1005,3,1999,14G + 1yr,Assigned,NaN
416,CH_32079,9.111002e+11,s2m_test_22158@tests2m.com,2020-04-27 00:00:00,SP_1005,2,1999,12G + 1yr,NaN,NaN
417,CH_32083,9.111002e+11,s2m_test_21404@tests2m.com,2020-04-27 00:00:00,SP_1012,4,1999,10G + 1Yr,Morning,NaN